#debug or release
run_mode = debug

[app]
jwt_secret = 23347$040412
jwt_issuer = gin-blog

[server]
http_port = 8000
read_timeout = 60
write_timeout = 60
log_path = logs/gin.log
log_level = debug

[database]
type = mysql
user = root
password = Qq659387
host = 127.0.0.1:3306
name = blog
table_prefix = blog_
charset = utf8mb4 
log_level = 4
